title: WP-HOSTING Dashboard
logo: https://wordpress.org/favicon.ico

header: true
footer: true

theme: dark

color: slate
layout:
  Control Panel:
    header: true
    style: row
    columns: 2 # Traefik, PMA
  Monitoring & Logs:
    header: true
    style: row
    columns: 2 # Netdata, Dozzle
  Server Tools:
    header: true
    style: row
    columns: 2 # Syncthing, DevTools

providers:
  openweathermap:
    apiKey: "{{HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY}}"
    units: metric
    cache: 5

widgets:
  - resources:
      cpu: true
      memory: true
      disk: /data
      label: System Load
      expanded: true
      refresh: 3000 # 3 sec refresh
